name: links

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 9 * * 1"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --accept 200,206,429 './**/*.md'
          fail: true
